version: '3.8'

services:
  
  jasma-pg-db:
    container_name: jasma-pg-db
    image: postgres:14.7-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose: 
      - 5432
    ports:
      - "5432:5432"
    networks:
      - jasma-network
    volumes: 
      - jasma-storage:/var/lib/postgresql/data

  jasma-redis-db:
    container_name: jasma-redis-db
    image: redis:7.0.10-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    expose: 
      - 6379
    ports:
      - '6379:6379'
    networks:
      - jasma-network
    volumes: 
      - jasma-storage:/redis-data

  jasma-api-server:
    container_name: jasma-api-server
    build:
      context: ./express
      target: production
      args:
        - START_FIRST_TIME=true
        - NODE_ENV=production
        - HOSTNAME=http://localhost
        - PORT=5000
        - SESSION_SECRET=keyboard cat
        - NEXTJS_ORIGIN=http://localhost
        - NEXTJS_PORT=3000
        - PG_SUPER_USER=postgres
        - PG_SUPER_PASSWORD=postgres
        - PG_ADMIN_USER=jasma_admin
        - PG_ADMIN_PASSWORD=a
        - PG_HOST=jasma-pg-db
        - PG_PORT=5432
        - PG_SUPER_DATABASE=postgres
        - PG_ADMIN_DATABASE=jasma_db
        - REDIS_HOST=jasma-redis-db
        - REDIS_PORT=6379
        - PAYPAL_SECRET=''
        - PAYPAL_CLIENT_ID_SANDBOX=''
        - PAYPAL_CLIENT_ID_PRODUCTION=''
        - STRIPE_SECRET_KEY=''
    restart: always
    image: jasma-api-server
    expose: 
      - 5000
    ports:
      - '5000:5000'
    networks:
      - jasma-network
    depends_on:
      - jasma-pg-db
      - jasma-redis-db

  jasma-client:
    container_name: jasma-client
    build:
      context: ./next
      target: production
      args:
        - BASE_URL=http://localhost
        - PORT=3000
        - NEXT_PUBLIC_API_SERVER_URL=localhost
        - NEXT_PUBLIC_API_SERVER_PORT=5000
        - NEXT_PUBLIC_NODE_ENV=production
        - ANALYZE=false
        - SESSION_SECRET=thisisatemporarysecret
        - PAYPAL_SECRET=''
        - NEXT_PUBLIC_PAYPAL_CLIENT_ID_SANDBOX=''
        - NEXT_PUBLIC_PAYPAL_CLIENT_ID_PRODUCTION=''
        - NEXT_TELEMETRY_DEBUG=1
        - NEXT_TELEMETRY_DISABLED=1
    restart: always
    image: jasma-client
    expose: 
      - 3000
    ports:
      - '3000:3000'
    networks:
      - jasma-network
    depends_on:
      - jasma-api-server

  jasma-nginx:
    container_name: jasma-nginx
    build:
      context: ./nginx
      target: production
    restart: always
    ports:
    - '80:80'
    networks:
      - jasma-network

volumes:
  jasma-storage:
    driver: local

networks:
  jasma-network:
    driver: bridge
